package com.dvn.vindecoder.util;

/**
 * Created by palash on 23-06-2016.
 */
public enum CallType {
    POST_SIGNUP, GET_PROFILE, POST_LOGIN, GET_SERVICES, UPDATE_PASSWORD, FORGOT_PASSWORD, PIN_CODE, SENT_REQUEST_TO_PROVIDER, ADD_CHILD, GET_SUBSERVICE, RECIPIE_DETAILS, ARTICAL_DETAILS, STORY_DETAILS,
    EVENTS_HIGH,CONTACTED_PROVIDER,LIKE_POST,GET_VEHICAL_LIST,POST_USER_SAVE,GET_USER_VEHICAL_LIST,GET_SELLER_USER_LIST,
    GET_VIN_DETAILS,GET_BUYER_LIST,GET_VIN_DETAILS_API_SERVER,GET_USER_VEHICAL_ASSIGN_LIST,UNASSIGNED_CAR_TO_USER,ASSIGNED_CAR_TO_USER,
    GET_VEHICAL_STEP_FIRST,GET_VEHICAL_STEP_SECOND,GET_VEHICAL_STEP_THIRD,GET_VEHICAL_STEP_FOURTH,GET_VEHICAL_STEP_FIFTH,
    GET_STOP_CAR
}
